language: go
go: 1.7

notifications:
 email: false

before_install:
 - go version

install:
 - go get github.com/Masterminds/glide

script:
 - glide install
 - go build -v
 - go test -v -race $(glide novendor)

