language: go
go: 1.7

notifications:
 email: false

before_install:
 - go version

install:
 - go get github.com/Masterminds/glide
 - go get -u github.com/golang/lint/golint

script:
 - glide install
 - go vet $(glide novendor)
 - golint $(glide novendor)
 - go build -v
 - go test -tags=integration -v -race $(glide novendor)

